import "./globals.css";

import { Montserrat } from 'next/font/google';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const font = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({children}) {
  return (
    <html lang="en" className={font.className}>
      <body className={font.className}>
          {children}
      </body>
    </html>
  );
}